# This is a basic workflow to help you get started with Actions

name: Print Pull Request

# Controls when the workflow will run
on:
  pull_request:
  
   branches:[ main ]


jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
      - name: Print "Hello World" and Pull Request details
        run: |
          echo "Hello World"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Last Commit: ${{ github.event.pull_request.head.sha }}"
          echo "Changes between last commit and default branch:"
          git diff  --no-index --name-only ${{ github.event.pull_request.base.sha }}..${{ github.event.pull_request.head.sha }}
