# This is a basic workflow to help you get started with Actions

name: Print Pull Request

# Controls when the workflow will run
on:
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  print-details:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Print "Hello World" and Pull Request details
      with:
        ref: ${{ env.GITHUB_SHA }}
      
        run: |
          echo "Hello World"
          echo "Author: ${{ github.event.pull_request.user.login }}"
          echo "Last Commit: ${{ github.event.pull_request.head.sha }}"
          echo "Changes between last commit and default branch:"
          echo "Last commit: $(git show -s --format=%s)";
          echo -e "Commit diff:\n$( git fetch && git diff origin/main..origin/firstAction )\n";
        shell: bash
